services:
  oracle-mcp:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - ./server/.env
    environment:
      - CACHE_DIR=/var/cache/oracle-mcp
      - TARGET_SCHEMA=${TARGET_SCHEMA:-}
      - THICK_MODE=${THICK_MODE:-0}
    volumes:
      - mcp_cache:/var/cache/oracle-mcp
      - ~/.oci:/root/.oci:ro
    ports:
      - "8000:8000"
    command: ["uv", "run", "server/main.py"]

  mcp-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - MCP_SERVER_URL=http://oracle-mcp:8000
      - OCI_COMPARTMENT_ID=${OCI_COMPARTMENT_ID:-}
      - OCI_AUTH_TYPE=${OCI_AUTH_TYPE:-SECURITY_TOKEN}
      - OCI_AUTH_PROFILE=${OCI_AUTH_PROFILE:-aryan-chicago}
      - OCI_MODEL_ID=${OCI_MODEL_ID:-openai.gpt-4.1-mini}
      - OCI_ENDPOINT=${OCI_ENDPOINT:-https://inference.generativeai.us-chicago-1.oci.oraclecloud.com}
    volumes:
      - ~/.oci:/root/.oci:ro
      - ~/.oci/config.container:/root/.oci/config:ro  # Use container-specific config
    depends_on:
      - oracle-mcp
    stdin_open: true
    tty: true

volumes:
  mcp_cache: