version: "3.8"

services:
  oracle-mcp:
    build:
      context: .
      dockerfile: Dockerfile.server  # Use server dockerfile
    env_file:
      - ./server/.env
    environment:
      - CACHE_DIR=/var/cache/oracle-mcp
      - TARGET_SCHEMA=${TARGET_SCHEMA:-}
      - THICK_MODE=${THICK_MODE:-0}
    volumes:
      - mcp_cache:/var/cache/oracle-mcp
      - ~/.oci:/root/.oci:ro
    ports:
      - "8000:8000"
    command: ["python", "server/main.py"]  # Run the server directly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mcp_cache: