services:
  oracle-mcp:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - ./server/.env
    environment:
      - CACHE_DIR=/var/cache/oracle-mcp
      - TARGET_SCHEMA=${TARGET_SCHEMA:-}
      - THICK_MODE=${THICK_MODE:-0}
    volumes:
      - mcp_cache:/var/cache/oracle-mcp
      - ~/.oci:/root/.oci:ro
    ports:
      - "8000:8000"
    command: ["uv", "run", "server/main.py"]

volumes:
  mcp_cache:
